
CC = gcc # Flag for implicit rules
CFLAGS = -g # Flag for implicit rules. Turn on debug info
blah: blah.o


blah.c:
	echo "int main() { return 0; }" > blah.c

# n.c -> n.o ::  $(CC) -c $(CPPFLAGS) $(CFLAGS)
# n.cpp -> n.o ::  $(CXX) -c $(CPPFLAGS) $(CXXFLAGS)
